//Use this like a service in Angular
module.exports =
                 [ { first_name : 'Rose',
                     last_name  : 'Tyler',
                     breed       : 'Whooping Marmot',
                     exp: 2,
                     eggs: 3,
                     img: 'brown-hen'},
                   { first_name : 'Zoe',
                     last_name  : 'Heriot',
                     breed       : 'Red Bellied Billy',
                     exp: 6,
                     eggs: 5,
                     img: 'black-and-white-hen'},
                   { first_name : 'Jo',
                     last_name  : 'Grant',
                     breed       : 'Osterlorpe',
                     exp: 5,
                     eggs: 3,
                     img: 'leopard-hen'},
                   { first_name : 'Leela',
                     last_name  : 'james',
                     breed       : 'Unspecified',
                     exp: 7,
                     eggs: 6,
                     img: 'white-hen'},
                   { first_name : 'Bob',
                     last_name  : null,
                     breed       : 'Gallifrey',
                     exp: 1,
                     eggs: 0,
                     img: 'leopard-hen'},
                   { first_name : 'Clara',
                     last_name  : 'Oswald',
                     breed       : 'Gilled Clucker',
                     exp: 3,
                     eggs: 2,
                     img: 'white-hen'},
                   { first_name : 'Adric',
                     last_name  : null,
                     breed       : 'Alzarius',
                     exp: 5,
                     eggs: 4,
                     img: 'light-brown-hen'},
                   { first_name : 'Susan',
                     last_name  : 'Foreman',
                     breed       : 'Crazed Silky',
                     exp: 6,
                     eggs: 6,
                     img: 'black-and-white-hen'} ];
